name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - run: mkdir -p ~/.aws/
      - run: echo "[techstarter]" > ~/.aws/credentials

      - run: echo "aws_access_key_id=$AWS_ACCESS_KEY" >> ~/.aws/credentials
        env: 
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      - run: echo "aws_secret_access_key=$AWS_SECRET_KEY" >> ~/.aws/credentials
        env: 
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - run: echo "aws_session_token=$AWS_SESSION_TOKEN" >> ~/.aws/credentials
        env:
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - run: cat ~/.aws/credentials

      - run: aws configure list-profiles
      - run: aws s3 ls --region eu-central-1 --profile techstarter
      - uses: hashicorp/setup-terraform@v2
      - run: npm run tf-version
      - run: npm run tf-init
      - run: npm run tf-val
      - run: npm run tf-plan
      - run: npm run tf-apply
      - run: aws s3 sync ./build s3://cicd-bucket-k1m0-738135 --profile techstarter
